version: '3.8'
services: 
    main:
      build: 
          context: .
          dockerfile: docker/Dockerfile
      command: 'php artisan serve --host=0.0.0.0'
      volumes:
        - ./src:/app
      networks:
        akl-network:
      ports:
        - 8880:8000
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
      volumes:
        - ./docker/init.sql:/data/application/init.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      networks:
        akl-network:
networks:
  akl-network: